frameworkVersion: "=1.4.0"

service: so-hot-right-now

provider:
  name: aws
  runtime: python2.7
  region: us-west-2
  cfLogs: true
  memorySize: 256
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:GetItem"
        - "dynamodb:UpdateItem"
      Resource: "arn:aws:dynamodb:us-west-2:111685254296:table/spotify"

package:
  exclude:
    - .git/**
    - .serverless/**
    - venv/**
    - '!venv/lib/python2.7/site-packages/**'
    - .gitignore
    - .editorconfig
    - requirements.txt

functions:
  handle:
    handler: handler.handle
    timeout: 30
    events:
      - schedule: cron(15 15 * * ? *)
