service: so-hot-right-now

provider:
  name: aws
  region: us-west-2
  runtime: python2.7
  memory: 128
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:GetItem"
        - "dynamodb:UpdateItem"
      Resource: "arn:aws:dynamodb:us-west-2:111685254296:table/spotify"

package:
  exclude:
    - .gitignore
    - .editorconfig
    - requirements.txt
    - .git

functions:
  handle:
    handler: handler.handle
    timeout: 15
    events:
      - schedule: cron(15 15 * * ? *)
